# Generated by Django 6.1.1 on 2026-10-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='referral_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
