# Generated by Django 6.1.1 on 2026-10-04 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_cashback_amount_product_referral_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cashback_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='referral_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='cashback_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% of profit shared with the buyer as cashback', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='referral_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% of profit shared with the referrer, if one exists', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
