# Generated by Django 6.1.1 on 2026-10-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_cashback_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashback_processed',
            field=models.BooleanField(default=False),
        ),
    ]
